# Generated by Django 3.1.6 on 2021-02-06 13:52

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('link', models.URLField(verbose_name='link')),
                ('image', models.ImageField(upload_to='images/offer/', verbose_name='image')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
            ],
        ),
    ]
