# Generated by Django 3.1.6 on 2021-03-21 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_remove_orderproduct_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('create_at',)},
        ),
    ]
